test: skip imagefile/test running from unit tests
imagefile/test are expected to run from e2e tests. Those are
accidentally being skipped from `make test` as those tests expect to
passed both REPO_ROOT and CLUSTER environment variables and REPO_ROOT
was not been set.

But with recent change REPO_ROOT is set for `make test`, which results
in running these tests and observed these failures:

```
01:45:42  --- FAIL: TestImageFile (3.08s)
01:45:42      --- FAIL: TestImageFile/ext4 (1.90s)
01:45:42          --g- FAIL: TestImageFile/ext4/512Mi (0.90s)
01:45:42              imagefiletest.go:114: running EXISTING_VM_FILE=/tmp/image866236566 PATH=/mnt/workspace/pmem-csi_PR-777/_work/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin RESOURCES_DIRECTORY=/mnt/workspace/pmem-csi_PR-777/_work/resources VM_IMAGE=/mnt/workspace/pmem-csi_PR-777/_work/pmem-govm/cloud-image.qcow2 check-imagefile.sh
01:45:42              imagefiletest.go:133: check-imagefile.sh: ERROR: cannot find actual file for /mnt/workspace/pmem-csi_PR-777/_work/pmem-govm/cloud-image.qcow2
```