test: catch unexpected modifications by operator
The operator had a bug where its change detection caused it to update
objects unnecessarily. This wasn't caught before by the tests because
the modified objects still had the expected content (as far as we
know, at least - https://github.com/intel/pmem-csi/issues/742 still
lacks a proper explanation).

Now the update unit test catches that bug:

    TestDeploymentController/Kubernetes_1.18/updating/pmemPercentage_in_default_deployment: deployment_controller_test.go:264:
        	Error Trace:	deployment_controller_test.go:264
        	            				deployment_controller_test.go:559
        	            				deployment_controller_test.go:584
        	Error:      	Received unexpected error:
        	            	deployed driver different from expected deployment:
        	            	object was modified unnecessarily: "pmem-csi-with-defaults-node" of type "apps/v1, Kind=DaemonSet" in namespace "test-namespace"
        	            	object was modified unnecessarily: "pmem-csi-with-defaults-controller" of type "apps/v1, Kind=StatefulSet" in namespace "test-namespace"
        	Test:       	TestDeploymentController/Kubernetes_1.18/updating/pmemPercentage_in_default_deployment
        	Messages:   	validate deployment

We cannot use the same validation during E2E testing because the app
controllers also modify the objects by setting their status.